#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 18 08:58:14 2021

@author: manuel
"""

events_dict = {'N01': {'lick_teach': 3, 'surgery': '-',
                       'sick': '-', 'wounds': '-'},
               'N02': {'lick_teach': 4, 'surgery': '20200203',
                       'sick': '-', 'wounds': '-'},
               'N03': {'lick_teach': 3, 'surgery': '20200203',
                       'sick': '-', 'wounds': '-'},
               'N04': {'lick_teach': 4, 'surgery': '20200203',
                       'sick': '-', 'wounds': '-'},
               'N05': {'lick_teach': 4, 'surgery': '20200205',
                       'sick': '20200206', 'wounds': '-'},
               'N06': {'lick_teach': 4, 'surgery': '-',
                       'sick': '-', 'wounds': '-'},
               'N07': {'lick_teach': 5, 'surgery': '20200205',
                       'sick': '20200206', 'wounds': '-'},
               'N08': {'lick_teach': 4, 'surgery': '20200205',
                       'sick': '20200206', 'wounds': '-'},
               'N09': {'lick_teach': 4, 'surgery': '-',
                       'sick': '-', 'wounds': '20191228'},
               'N10': {'lick_teach': 4, 'surgery': '-',
                       'sick': '-', 'wounds': '20191227'},
               'N11': {'lick_teach': 3, 'surgery': '20200205',
                       'sick': '20200206', 'wounds': '-'},
               'N12': {'lick_teach': 4, 'surgery': '20200205',
                       'sick': '-', 'wounds': '-'},
               'N13': {'lick_teach': 4, 'surgery': '20200205',
                       'sick': '20191220', 'wounds': '-'},
               'N14': {'lick_teach': 5, 'surgery': '20200106',
                       'sick': '-', 'wounds': '-'},
               'N15': {'lick_teach': 4, 'surgery': '-',
                       'sick': '-', 'wounds': '-'},
               'N16': {'lick_teach': 4, 'surgery': '20200203',
                       'sick': '-', 'wounds': '-'},
               'N17': {'lick_teach': 5, 'surgery': '20200203',
                       'sick': '-', 'wounds': '-'},
               'N18': {'lick_teach': 4, 'surgery': '-',
                       'sick': '-', 'wounds': '-'},
               'N19': {'lick_teach': '-', 'surgery': '-',
                       'sick': '20200803', 'wounds': '-'},
               'N20': {'lick_teach': '-', 'surgery': '-',
                       'sick': '-', 'wounds': '-'},
               'N21': {'lick_teach': '-', 'surgery': '-',
                       'sick': '-', 'wounds': '-'},
               'N22': {'lick_teach': '-', 'surgery': '-',
                       'sick': '-', 'wounds': '-'},
               'N23': {'lick_teach': '-', 'surgery': '-',
                       'sick': '-', 'wounds': '-'},
               'N24': {'lick_teach': '-', 'surgery': '-',
                       'sick': '-', 'wounds': '-'},
               'N25': {'lick_teach': '-', 'surgery': '-',
                       'sick': '-', 'wounds': '-'},
               'N26': {'lick_teach': '-', 'surgery': '-',
                       'sick': '-', 'wounds': '-'},
               'N27': {'lick_teach': '-', 'surgery': '-',
                       'sick': '-', 'wounds': '-'},
               'N28': {'lick_teach': '-', 'surgery': '-',
                       'sick': '-', 'wounds': '-'}}